### ISSUE TITLE
googleapi: Error 403: Cannot update a published APK., forbidden

### ISSUE THREAD

**Issue by PabloSSena** [bitrise-steplib/steps-google-play-deploy#103]
Hello, thanks for reading this issue, I'm having this problem when I try to update an app.

Create new edit
 editID: 16802875446992048661
Edit insert created
Upload apks or app bundles
Found .apk file: /Users/vagrant/git/platforms/android/app/build/outputs/apk/release/app-release-bitrise-signed.apk
Uploading /Users/vagrant/git/platforms/android/app/build/outputs/apk/release/app-release-bitrise-signed.apk 1/1
Failed to upload APKs: failed to upload apk, error: googleapi: Error 403: Cannot update a published APK., forbidden
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | google-play-deploy@3 (exit code: 1)                           | 23.03 sec|
+---+---------------------------------------------------------------+----------+

I have no idea how to fix it. Hope someone can help me, thanks

**Comment by PabloSSena** [comment]
I solved it.

**Comment by chaitanyatanna-bitrise** [comment]
Awesome @PabloSSena 

Chaitanya
