### ISSUE TITLE
This step does not promote to another track

### ISSUE THREAD

**Issue by pmourawill** [bitrise-steplib/steps-google-play-deploy#104]
Failed to upload APKs: failed to upload app bundle, error: googleapi: Error 403: APK specifies a version code that has already been used., forbidden

`Getting configuration
Configs:
- JSONKeyPath: *****
- PackageName: confidential
- AppPath: /bitrise/deploy/1.34-377.aab
- ExpansionfilePath: 
- Track: alpha
- UserFraction: 0
- UpdatePriority: 5
- WhatsnewsDir: 
- MappingFile: /bitrise/deploy/app-mapping.txt
Found .aab file: /bitrise/deploy/1.34-377.aab
Configuration read successfully
Authenticating
Authenticated client created
Create new edit
 editID: confidential
Edit insert created
Upload apks or app bundles
Found .aab file: /bitrise/deploy/1.34-377.aab
Uploading /bitrise/deploy/1.34-377.aab 1/1
Failed to upload APKs: failed to upload app bundle, error: googleapi: Error 403: APK specifies a version code that has already been used., forbidden`

This step does not update/promote versions to another track.
It generates an editId for nothing...

Is there any other way to promote a release that is on specific track e.g. 'beta' to another one e.g. 'production' without an another artifact unnecessary upload?

**Comment by bitce** [comment]
Hi @pmourawill!

This step exist to deploy to the Play Store mainly, so if that's not what you are looking to do exactly, we wouldn't recommend using it. Maybe you could write an API call to do this based on the possibilities here? https://developers.google.com/android-publisher

**Comment by pmourawill** [comment]
We've decided to use another strategy for version promotion for now.
But, we are planning to release some step that just change the track instead of uploading an artifact every time.

Thanks for responding!
