### ISSUE TITLE
Failed to validate edit, error: googleapi: Error 500: Internal error encountered., backendError

### ISSUE THREAD

**Issue by NarongkornPad8** [bitrise-steplib/steps-google-play-deploy#106]
Hi! I trying to deploy application by google-play-deploy version 3.1.2. But have error this :

Update track
Release version codes are: [20]
alpha track will be updated.
 updated track: alpha
Track updated
Validating edit
Failed to validate edit, error: googleapi: Error 500: Internal error encountered., backendError

**Comment by luna-kx** [comment]
Hi @NarongkornPad8,

Thank you for reaching out.

Can you please share a build link and enable support access so I can take a look at your builds?

**Comment by NarongkornPad8** [comment]
I submit location policy in Google Play and deploy again. I deploy completed. 

Thanks so much.
