### ISSUE TITLE
Failed to validate edit, error: googleapi: Error 403: Release artifacts require permissions that are missing from permission declaration.

### ISSUE THREAD

**Issue by Hao-Cognativ** [bitrise-steplib/steps-google-play-deploy#107]
Hi Team,

This step was working perfectly on the last build(1.4) but it was broken last night(1.5) due to this 403 error. Meanwhile, there has been no changes on the service account side.
`[34;1mValidating edit[0m
[31;1mFailed to validate edit, error: googleapi: Error 403: Release artifacts require permissions that are missing from permission declaration., forbidden[0m`

And here is the build url for your convenience: https://app.bitrise.io/build/da4bfd8c129331e9#?tab=log

**Comment by chaitanyatanna-bitrise** [comment]
Hi @Hao-Cognativ 
Can you make sure to update the app version you are trying to deploy
https://stackoverflow.com/questions/54564800/google-api-error-permissiondeclarationrequiresupdate

Thanks
Chaitanya

**Comment by Hao-Cognativ** [comment]
Hi @chaitanyatanna-bitrise,
Thanks for reaching out.
Turned out google updated their sensitive data declaration, not on Bitrise.
It's has been fixed and I will close this issue.

Regards,
Hao
