### ISSUE TITLE
Bug - 502

### ISSUE THREAD

**Issue by billnbell** [bitrise-steplib/steps-google-play-deploy#108]
Started getting this error.
Committing edit
Failed to commit edit, error: googleapi: got HTTP response code 502 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

**Comment by trestini** [comment]
Same here.
It appear to be a problem with Google, but I've tried 3 builds in a 3 hours timeframe with the same error.

**Comment by billnbell** [comment]
OK any way to fix it? Did they change their Authentications?

**Comment by bandojulio** [comment]
I got the same error but my .aab was uploaded successfully to the play store. Just got my pipeline broken because of the 502 error

**Comment by billnbell** [comment]
same here. It uploaded but I get a 502.

**Comment by bandojulio** [comment]
I've put this step as the last one in my pipeline since it's uploading successfully.
I looking for release notes or system status of the Google Play Android Developer API, if someone find it we can check if some major chance broke this step.

**Comment by WXSoftware** [comment]
> I've put this step as the last one in my pipeline since it's uploading successfully.
> I looking for release notes or system status of the Google Play Android Developer API, if someone find it we can check if some major chance broke this step.

The same here. Version used for google-play-deploy 3.0.2

Request:

Failed to commit edit, error: googleapi: got HTTP response code 502 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

**Comment by jeanremy** [comment]
Same here. Upload works, but google-play-deploy fails. Is it related to Google [changing their routes](https://twitter.com/flexbox_/status/1352257931505512448) ?

**Comment by bitce** [comment]
Hey everyone! Sorry to hear about the errors, we're looking at this right away. Can anyone provide a link to their build URL or a logfile? That would be helpful in further digging into this. 

Thanks!

**Comment by adebree** [comment]
> Hey everyone! Sorry to hear about the errors, we're looking at this right away. Can anyone provide a link to their build URL or a logfile? That would be helpful in further digging into this.
> 
> Thanks!

I've reached out to you on the Bitrise slack for this

**Comment by mabdurrahman** [comment]
I'm experiencing the same issue too, clearly, it's an issue from Google side as I can get a similar issue when I upload the build manually from Google Play Console just after clicking on "Start rollout to Internal testing":
```
An unexpected error has occurred. Please try again. (5039F17F)
```

**Comment by androideveloper** [comment]
The same here

**Comment by MarcosEduardoJr** [comment]
The same here, pls save us im crying

**Comment by noakk** [comment]
The same here =/////

**Comment by mackoj** [comment]
same here

**Comment by duy-ng-12354** [comment]
Same here. the app is deployed successfully but we cannot be comfortable with a 'red' build.

![image](https://user-images.githubusercontent.com/41779676/105623985-b317ad00-5e50-11eb-9332-b92999bef7d8.png)

**Comment by jamie1192** [comment]
Chiming in to say me too, this has been happening for us since Thursday.

Any specific information I can pass on that can help?

**Comment by rizkyfadillah** [comment]
Same here. However, the build was successfully uploaded to Play Store.

<img width="1289" alt="Screen Shot 2021-01-25 at 10 08 21" src="https://user-images.githubusercontent.com/6652893/105656648-44405f80-5ef5-11eb-92f5-6bb4650f1035.png">

**Comment by ndbeyer** [comment]
Same here

**Comment by adebree** [comment]
@bitce Any news on this? Maybe the step can be adjusted so the editing of the details is not performed since uploading the artifact itself is working.

**Comment by billnbell** [comment]
Status? It has been almost a week.

**Comment by bitce** [comment]
Hey everyone!

There is no documentation/communication from Google about this change that would cause this, so we've reached out to them, hoping we can address this soon. 

In the meanwhile, while this is still an alarming problem, deployments should still succeed despite the failing step/builds.

**Comment by duy-ng-12354** [comment]
> Same here. the app is deployed successfully but we cannot be comfortable with a 'red' build.
> 
> ![image](https://user-images.githubusercontent.com/41779676/105623985-b317ad00-5e50-11eb-9332-b92999bef7d8.png)
> 
> Please help to address this issue.
> 
> Thanks a lot.

Today, it works on my side without any changes.

**Comment by adebree** [comment]
I have the same observation, it started to work again on our projects without changes from our side.

**Comment by ndbeyer** [comment]
Seems to work again
