### ISSUE TITLE
Failed to create publisher service, error: google: could not find default credentials.

### ISSUE THREAD

**Issue by steven-spiel** [bitrise-steplib/steps-google-play-deploy#110]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.1.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I'm trying to deploy to Google Play. I followed the instructions provided

<details>
  
Uploads and releases apps to Google Play Store.

The step supports single APK, multiple APK and Bundle deploys.

To use this step:

Upload the first apk manually (using the web interface):

Visit the Google Play Console -> All applications -> CREATE APPLICATION

Link your Google Play Developer Console to an API project:

Described in Google Play Developer API's Linking your API Project section

Setup API Access Clients, using a service account:

Described in Google Play Developer API's Using a service account section

NOTE: When you create your service account on the Google Play Developer Console, choose json as Key Type.

Grant the necessary rights to the service account:

Visit the Google Play Console -> Settings -> Users & permissions -> Invite new user.

Due to the way the Google Play Publisher API works, you have to grant at least the following permissions to that service account:

ACCESS LEVEL: View app information
RELEASE MANAGEMENT: Manage production releases, Manage testing track releases
STORE PRESENCE: Edit store listing, pricing & distribution
OPTIONAL - Add translations for your Store Listing:

To allow the step to assign your 'whatsnew' files to the uploaded apk version.

Visit Play Console Help's Add translations for your Store Listing section</details>

### Bitrise info

- [Build URL](https://app.bitrise.io/build/4cad6cbc2fb7adc8#?tab=log)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log:

<details>
  <pre>
 +------------------------------------------------------------------------------+

| (2) google-play-deploy@3                                                     |
+------------------------------------------------------------------------------+
| id: google-play-deploy                                                       |
| version: 3.1.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-02-01T15:57:24Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Getting configuration
Configs:
- JSONKeyPath: *****
- PackageName: com.transcarent.app
- AppPath: /Users/vagrant/deploy/app-release.apk\n
- ExpansionfilePath: 
- Track: internal
- UserFraction: 0
- UpdatePriority: 0
- WhatsnewsDir: 
- MappingFile: 
Found .apk file: /Users/vagrant/deploy/app-release.apk
Configuration read successfully
Authenticating
Failed to create publisher service, error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | google-play-deploy@3 (exit code: 1)                           | 23.07 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-google-play-deploy/issues |
| Source: https://github.com/bitrise-io/steps-google-play-deploy               |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

**Comment by ofalvai** [comment]
Hi @steven-spiel,

For the service account key path of the Google Play step, it looks like you used an incorrect path to a JSON file. The service account key JSON file should be uploaded to [Generic File Storage](https://devcenter.bitrise.io/tutorials/how-to-use-the-generic-file-storage/#uploading-files-to-generic-file-storage-on-bitriseio), and later referenced from the Google Play step by an environment variable name (double-check that you use the correct one, there are a few env vars related to code signing and secrets in general)

**Comment by steven-spiel** [comment]
Thank you. Got it working
