### ISSUE TITLE
Incorrect issue management settings

### ISSUE THREAD

**Issue by koral--** [bitrise-steplib/steps-google-play-deploy#112]
This PR was marked as off-topic:
https://github.com/bitrise-steplib/steps-google-play-deploy/pull/111#issuecomment-775155006

However, I see no off-topic there.
@mateherber could you explain that?

**Comment by mateherber** [comment]
Hi @koral-- ,

I've opened that pr then had been told that markdown handles just `1.` for all lines for numbered lists so I closed the PR. `off-topic` was the closest reason to close discussion there.

**Comment by koral--** [comment]
My intent was to point only the possible misconfiguration of automated closing to avoid such inconsistencies in the future.

**Comment by mateherber** [comment]
Yeah no automation was involved, I just closed it as the change was no longer needed. I'm closing this issue if you don't mind.

**Comment by koral--** [comment]
Ah, OK, thanks for explanation :)
