### ISSUE TITLE
googleapi: Error 500: Internal error encountered., backendError

### ISSUE THREAD

**Issue by sosite** [bitrise-steplib/steps-google-play-deploy#114]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.2.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME

### Issue description

During deploy bundle to Google Play step hits internal error from Google Play. The bug occurs after "Validating edit". Previously everything works fine, it's just stopped worked without any changes from our side. This problem occurred in 2 independent project at the same time.

### Bitrise info

- Build URL: (1st app) https://app.bitrise.io/build/e6f9bc542c49fa39, (2nd app) https://app.bitrise.io/build/bf32af28c888ce65
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
+------------------------------------------------------------------------------+
| (3) google-play-deploy                                                       |
+------------------------------------------------------------------------------+
| id: google-play-deploy                                                       |
| version: 3.2.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-03-17T13:40:43Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Getting configuration
Configs:
- JSONKeyPath: *****
- PackageName: my.com.kaf.tradeclub
- AppPath: /bitrise/deploy/app-kaf-production-release-bitrise-signed.aab
- ExpansionfilePath: 
- Track: internal
- UserFraction: 0
- UpdatePriority: 0
- WhatsnewsDir: 
- MappingFile: /bitrise/deploy/app-mapping.txt
- ReleaseName: 
Found .aab file: /bitrise/deploy/app-kaf-production-release-bitrise-signed.aab
Configuration read successfully
Authenticating
Authenticated client created
Create new edit
 editID: 00397524266102971796
Edit insert created
Upload apks or app bundles
Found .aab file: /bitrise/deploy/app-kaf-production-release-bitrise-signed.aab
Uploading /bitrise/deploy/app-kaf-production-release-bitrise-signed.aab 1/1
Uploaded app bundle version: 449
 uploaded mapping file for apk version: 449
Done uploading of 1 apps
New version codes to upload: 449
Applications uploaded
Update track
Release version codes are: [449]
internal track will be updated.
 updated track: internal
Track updated
Validating edit
Failed to validate edit, error: googleapi: Error 500: Internal error encountered., backendError
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | google-play-deploy (exit code: 1)                             | 42.07 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-google-play-deploy/issues |
| Source: https://github.com/bitrise-io/steps-google-play-deploy               |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

1. Simple deploy bundle to the Google Play

**Comment by rem821** [comment]
Having the same issue on multiple projects

**Comment by rem821** [comment]
Having the same issue on multiple projects

**Comment by david-jarvis** [comment]
I'm also experiencing this issue

**Comment by hnljp** [comment]
same here.
I have tried to contact Google.

**Comment by nico-gonzalez** [comment]
Same here 😢

**Comment by carlosguerreroo** [comment]
Same Here :(

**Comment by amir-dropit** [comment]
#metoo

**Comment by nghiadoan91** [comment]
me too

**Comment by carrymaster** [comment]
same

**Comment by hnljp** [comment]
Maybe it is time to update the androidpublisher code... at the moment this step is using one year old code (from 20200317).

https://github.com/googleapis/google-api-go-client/tree/master/androidpublisher/v3

**Comment by mikeislearning** [comment]
Ditto

**Comment by ofalvai** [comment]
Hey, we are aware of the issue, but looks like it's a problem on Google's end. We tried updating the library dependency in #115 (thanks @hnljp for the suggestion!), but our end-to-end tests are still failing after the change.

**Comment by hnljp** [comment]
> Hey, we are aware of the issue, but looks like it's a problem on Google's end. We tried updating the library dependency in #115 (thanks @hnljp for the suggestion!), but our end-to-end tests are still failing after the change.

Thank you very much.
When I get a reply from Google, am I going to let you know.

**Comment by hnljp** [comment]
A deploy has finally finished successfully.

**Comment by mateherber** [comment]
Hi @sosite,

Thank you for the report. We've released a new step version which has the Google API dependency updated to the latest version. The issue was probably resolved on Google's side though.

Please test the step yet again and let us know if the problem has been resolved. If so we can close the issue.

**Comment by hnljp** [comment]
> Hi @sosite,
> 
> Thank you for the report. We've released a new step version which has the Google API dependency updated to the latest version. The issue was probably resolved on Google's side though.
> 
> Please test the step yet again and let us know if the problem has been resolved. If so we can close the issue.

Thank you very much.
When will 3.2.2 be available on bitrise?
I can still only see 3.2.1.

I am going to test it when it is possible to choose it.

**Comment by hnljp** [comment]
@mateherber 
I have now tested and it is working and it is so far working well with 3.2.2
Have tested it about 40 times.

**Comment by mateherber** [comment]
Thank you @hnljp!

I'm happy that it got resolved. I'll close this issue after a couple of days then.

**Comment by mateherber** [comment]
Closing this as it seems to be resolved. Should you encounter the same or similar problem, please open a new issue
