### ISSUE TITLE
Failed to upload APKs: failed to upload app bundle, error: googleapi: Error 403: The Android App Bundle contains an auto-generated multi-apk that exceeds the maximum allowed size of 150 MB., forbidden

### ISSUE THREAD

**Issue by cadaniel** [bitrise-steplib/steps-google-play-deploy#117]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.3.0
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Unable to upload the built app to the play store. 

### Bitrise info

- Build URL: https://app.bitrise.io/build/25e5587056cd4148#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES 
- Log: 

<details>
  <pre>
Upload apks or app bundles
Found .aab file: /Users/vagrant/deploy/app-prod-release.aab
Uploading /Users/vagrant/deploy/app-prod-release.aab 1/1
Failed to upload APKs: failed to upload app bundle, error: googleapi: Error 403: The Android App Bundle contains an auto-generated multi-apk that exceeds the maximum allowed size of 150 MB., forbidden
  </pre>
</details>

### Steps to reproduce

1. ...
2. ...

**Comment by mateherber** [comment]
Hi @cadaniel 

Thank you for reporting this issue for us. 

The size of one of your `*.apk` that is generated from your `*.aab` exceeds the `150 MB` limit set by Google. 

https://developer.android.com/guide/app-bundle/#size_restrictions

Please make sure the bundle generation is set-up properly in your `build.gradle`'s `android{}` block. For instance if you're using native libraries make sure split by `abi` is enabled

```
bundle {
   abi {
       enableSplit = true
   }
}
```

A great article on the subject here: https://medium.com/@jitsm555/introduction-to-android-app-bundle-1c402d3a938e

Please let me know if this helps or we need to look into this further.
