### ISSUE TITLE
suddenly failing on "validating edit" related to "changesNotSentForReview"

### ISSUE THREAD

**Issue by thenderson55** [bitrise-steplib/steps-google-play-deploy#119]
My Android build was working fine then suddenly broke on "validating edit" and now fails every attempt to rebuild

version 3.3.0

Build URL:  https://app.bitrise.io/build/4ee6640df3f05b3e#?tab=log

```
Validating edit
Failed to validate edit, error: googleapi: Error 400: Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI., badRequest
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | google-play-deploy@3 (exit code: 1)                           | 31.78 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-google-play-deploy/issues |
| Source: https://github.com/bitrise-io/steps-google-play-deploy               |
+---+---------------------------------------------------------------+----------+
```

**Comment by HaswinVidanage** [comment]
Same here, 

Is google-deploy step going to support this change?
https://developers.google.com/android-publisher/api-ref/rest/v3/edits/commit

**Comment by lpusok** [comment]
Hello, @thenderson55 @HaswinVidanage 
Looking into this issue. Do you have any idea why would this happen? Is it due to the the slower review times?

![All_apps](https://user-images.githubusercontent.com/7979773/117970738-4d7cfd00-b329-11eb-90bd-373d2f6d3174.jpg)

Why would uploading to internal track require review? Can you share the current status of the app shown here:
![All_apps](https://user-images.githubusercontent.com/7979773/117970833-6edde900-b329-11eb-8383-95c5c0afcb5e.jpg)

If this error is received, should we retry with the `changesNotSentForReview` set to true in all cases?

**Comment by thenderson55** [comment]
Ah, yes - there was some rejection in Google Play store - it now deploys successfully.

**Comment by declan-betmate** [comment]
@thenderson55 that's interesting, can you find out what the change in Google Play was at all? We're having the same issue.

**Comment by HaswinVidanage** [comment]
@thenderson55  could you let us know what the change was?

**Comment by thenderson55** [comment]
This was the response I got from the guy who changed something then it could deploy:

```
The reason the staging version was rejected was "About the Content Ratings policy".
It seems that this was not a problem such as coding, but the problem was that the explanation of the service was reminiscent of "matching/dating service".

According to the staging version, it said "Action required", so it may be built successfully if I modify the explanation. I'll correct it tonight, so please try to build it again tomorrow.
```

So it was showing a rejection and he received an email then changed to the description/explanation and it can build now.

**Comment by HaswinVidanage** [comment]
Thanks @thenderson55 

ok in that case this only happens when there's an existing app rejection from the play store. so a workaround would be for us to first resolve that rejection and submit again.

**Comment by mateherber** [comment]
We introduced a flag in `3.4.0` where users can decide whether the step should fail when it fails to send the changes to review automatically. The step can handle retrying by providing the `changesNotSentForReview`. This is the best that is achievable with these new restrictions.

I'll close this issue now, please try the new step version, and should you experience anything out of order, please open another issue.
