### ISSUE TITLE
failed to create auth config from json key file

### ISSUE THREAD

**Issue by Cash39406** [bitrise-steplib/steps-google-play-deploy#148]
I tried to deploy aab file to play store but encountered this error:

Authenticating
Failed to create HTTP client: failed to create auth config from json key file [REDACTED], error: %!s(<nil>)
Failed to create HTTP client: failed to create auth config from json key file [REDACTED], error: %!s(<nil>)

Log is here: https://app.bitrise.io/build/ce924ad0-619d-4cea-a099-dd089e7c820c

**Comment by rsweny** [comment]
For me I had to do the opposite of what the instructions say.. just upload the json key file under "Code Signing and Storage" and copy the variable that begins with $BITRISEIO_ .... _URL and use that in the "Deploy to Google Play" step.

Use this variable directly and do not create a secret that holds it. Hiding an environment var name behind a secret did seem rather pointless as it is the url that needs to be kep secret.
