### ISSUE TITLE
error: googleapi: Error 401: Request is missing required authentication credential

### ISSUE THREAD

**Issue by DavidAZimmerly** [bitrise-steplib/steps-google-play-deploy#153]
### Troubleshooting

- [ x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.7.3
- Is the issue reproducible with the latest version? It happens sporadically with latest version
- Does the issue happen sporadically, or every time? SPORADIC
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

When running the google play deploy step, I **_occasionally_** get a failure with:
Failed to upload application(s): failed to upload app bundle, error: googleapi: Error 401: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., unauthorized

### Bitrise info

- Build URL:  https://app.bitrise.io/build/b48a3369-e0d3-46a9-9013-c4dcbf027a98
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
Getting configuration
Configs:
- JSONKeyPath: *****
- PackageName: com.arcxp.thearcxp
- AppPath: /bitrise/deploy/app-arcXPInternal-release.aab
- ExpansionfilePath: 
- Track: internal
- UserFraction: 0
- UpdatePriority: 0
- WhatsnewsDir: 
- MappingFile: 
- ReleaseName: 
- Status: 
- RetryWithoutSendingToReview: false
- AckBundleInstallationWarning: false
Using app from: /bitrise/deploy/app-arcXPInternal-release.aab
Configuration read successfully
Authenticating
Authenticated client created
Create new edit
 editID: 05832712845556463172
Edit insert created
Available tracks on Google Play:
- production
- beta
- alpha
- internal
- Investigation
- ReleaseCandidate
Tracks listed
Upload apks or app bundles
Uploading /bitrise/deploy/app-arcXPInternal-release.aab 1/1
Failed to upload application(s): failed to upload app bundle, error: googleapi: Error 401: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., unauthorized
  </pre>
</details>

### Steps to reproduce

unsure, it happens regularly though

**Comment by mmiller-wfc** [comment]
This started happening for our account as well (as of today 9/15/23). Some builds deploy successfully and some fail with the same error.

**Comment by richdapice** [comment]
The same is happening today for us as well.

**Comment by sebastian-zero** [comment]
Same, our Android builds fail constantly now.

**Comment by daniel-zero** [comment]
Fastlane was able to find a workaround: https://github.com/fastlane/fastlane/pull/21518

**Comment by jaymengxy** [comment]
I encountered the same issue yesterday.

**Comment by dranoer** [comment]
We faced the same issue today.

**Comment by CrazyScrubber** [comment]
Same issue since last week

**Comment by martyphee** [comment]
Having issues also and I'm using 3.7.4

**Comment by sameermore412** [comment]
Encountered the same issue. Version 3.7.4 was used when it failed.

**Comment by lpusok** [comment]
Version 3.7.4 retries 4 times with relatively short wait (1, 2, 4 and 8 seconds). There is a `verbose_log` input you can set to true to see these in the log. Version 3.7.5 retires more times with more wait time (2, 4, 8, 16, 30 and 30 seconds).

I recommend to report the 401 status issue to Google Play at https://support.google.com/googleplay/android-developer/contact/general_contact.

**Comment by martyphee** [comment]
3.7.5 seems to have fixed the issue. At least my last build worked

**Comment by CrazyScrubber** [comment]
3.7.5 => Still have the same issue

**Comment by J6ey** [comment]
@CrazyScrubber Also not able to upload with mapping file. Are you saying it uploads fine without it?

**Comment by CrazyScrubber** [comment]
@J6ey 
Yes. We got the following error
`Failed to upload application(s): failed to upload mapping file, error: googleapi: Error 401: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., unauthorized`

The upload of the app bundle works but the mapping file is causing us the 401 exception.
It just works every 10 tries of restarting the build

**Comment by lpusok** [comment]
@CrazyScrubber can you share a log with verbose_log enabled?

**Comment by lpusok** [comment]
Anecdotally recreating the Google Play service account can help, maybe worth a try.

**Comment by jordan819** [comment]
Same problem here: can't deploy 2 out of 20 applications due to authorization error. I've tried several times and get exactly the same error.

`Failed to upload application(s): failed to upload app bundle, error: googleapi: Error 401: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., unauthorized`

**Comment by CrazyScrubber** [comment]
OK with verbose_log it is the same app bundle issue as before. There were 6 Tries but every time 401.
We deploy multiple apps with one Build. Sometimes 2 of three will be uploaded to Google Play and the last one gets the 401.
`Failed to upload application(s): failed to upload app bundle, error: googleapi: Error 401: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., unauthorized`

**Comment by anthony-fresneau-kiplin** [comment]
3.7.5 => Still have the same issue.

**Comment by koral--** [comment]
@lpusok here is the log of the build failed for the same reason. Support access granted: https://app.bitrise.io/build/183b9a60-dc54-4063-a6bb-550b48475c60

**Comment by ruialmeida51** [comment]
+1 Also having the same issue using the latest version.

**Comment by labreu-bc** [comment]
Same issue here, we're on 3.7.5, multiple attempts for the past couple of hours and only 1 got through

**Comment by loopyzort** [comment]
same here, cannot upload our builds to the play store anymore using 3.7.5

**Comment by empowerDan** [comment]
Same.

**Comment by Ahmadin29** [comment]
Same issue on latest version

**Comment by minalaroraswiggy** [comment]
same issue

**Comment by scruffyfox** [comment]
Same issue with 3.7.x

80% of builds are failing

**Comment by valls** [comment]
Same issue, 
Previous deploy with version 3.7.3 on 8/29/23 working ✅ 
Last deploy with version 3.7.5 on 9/20/23 failing ❌

**Comment by xcibik00** [comment]
Same issue

**Comment by martyphee** [comment]
Failing again for me

**Comment by lpusok** [comment]
It seems we can not fix this without involvement from Google Play developer support. Reached out, waiting for a response.

Would like to try a different approach: _Please remove the Step from frequently triggered workflows_ (manual trigger is ok). [Release Management ](https://devcenter.bitrise.io/en/release-management.html) can be also an alternative the meantime.
Whatever the issue is, bombarding the Google APIs with requests is not helping, so that is why want to try this. Thanks.

**Comment by loopyzort** [comment]
I'm not sure if this is related, but after these problems, I manually uploaded an apk and the Play Store had a new Financial Products policy I needed to accept. After doing that, my last 2 executions of the task have worked. using version 3.7.5

**Comment by GrahamBorland** [comment]
It's not related to Financial Products. We submitted that declaration a few weeks ago, and have been hitting this error much more recently.

**Comment by GrahamBorland** [comment]
Discussion and possible resolution in this thread:
https://androidstudygroup.slack.com/archives/C51GTR17A/p1695146387223879

**Comment by scruffyfox** [comment]
@GrahamBorland can you post the solution here for those without slack access?

**Comment by GrahamBorland** [comment]
The possible solution may not be the answer after all, but the suggestion was to make sure the tools are on the latest version of the `androidpublisher` npm package. Maybe it doesn't apply here at all.

Sorry for giving false hope...

**Comment by RichardLima** [comment]
same issue on 3.7.x
we used 3.6.x as workaround and it worked

**Comment by J6ey** [comment]
3.6.x  is working on my end too. I also had to stop sending the mapping file or it would error out the same way

**Comment by Ahmadin29** [comment]
Working well after downgrade to 3.6.x

**Comment by bbq-all-stars** [comment]
I had the same issue, but after downgrading to 3.6.x it's working completely.

**Comment by lpusok** [comment]
Good news everyone Google finally fixed the issue based on Step success rates.
