### ISSUE TITLE
Publishing: error 500 from Google !?

### ISSUE THREAD

**Issue by Bubelbub** [bitrise-steplib/steps-google-play-deploy#17]
Hey guys,

I uploaded the app via this step and always getting this.

    Failed to commit edit, error: googleapi: got HTTP response code 500 with body: {
     "error": {
      "code": 500,
      "message": null
     }
    }

But in the first builds it works. There I got a version problem.

    Upload apks
    Failed to upload apk, error: googleapi: Error 403: APK specifies a version code that has already been used.,     apkUpgradeVersionConflict
    |                                                                              |
    +---+---------------------------------------------------------------+----------+
    | x | google-play-deploy@1.1.0 (exit code: 1)                       | 15 sec   |

**Comment by trapacska** [comment]
Hey @Bubelbub !

Thanks for the report, we will investigate the issue soon! 
🚀

**Comment by Bubelbub** [comment]
Maybe you can explain me how to debug it a bit more.
If you send me your mail address I can give you the json file and everything.
After you checked it I can refresh the credentials 👍

**Comment by Bubelbub** [comment]
Hmm now it work's so don't know if there was a Google problem or something else.
I changed nothing.

![2017-03-22 12_23_36-fotos](https://cloud.githubusercontent.com/assets/319352/24195574/95475a22-0efa-11e7-8f97-6e2962808679.png)

**Comment by trapacska** [comment]
Yep, it seems like google's server sent back an internal server error: StatusCode 500. This can be a temporary service outage by Google. 

So further investigations are not required for the step, as it has no bug in this case, so I close this issue.
However I've set a card in our internal todo tracker in regards of implementing a retry for this command in case of StatusCode 500 response.

Thank you for the feedback @Bubelbub ! 🚀🎉
