### ISSUE TITLE
Breaking change back in Oct? [regression]

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-steplib/steps-google-play-deploy#19]
This change https://github.com/bitrise-steplib/steps-google-play-deploy/pull/10/files#diff-91d8d269a1c9bd3631ddb04b80b01c4eL64 seems to break the key input. Previously local files in the format `./path/to/file` were accepted, but right now only `file://./path/to/file` is accepted.

If possible we should allow the `./path/to/file` specification too.

**Comment by trapacska** [comment]
This release:

https://github.com/bitrise-steplib/steps-google-play-deploy/releases/tag/1.2.2

fixes the issue, thank you for reporting! 🎉
