### ISSUE TITLE
How to define mappings.txt path in bitrise config?

### ISSUE THREAD

**Issue by uddyami** [bitrise-steplib/steps-google-play-deploy#21]
I see in Changelog.md that upload mapping.txt is now in plugin but i cannot find how to configure that.

**Comment by godrei** [comment]
Hi @uddyami ,
thanks for the issue!
Currently the step does not handle the mapping.txt file.
I scheduled to fix this!

**Comment by uddyami** [comment]
Hey @godrei Just checking up if we have updates for this ^^

**Comment by cookseym** [comment]
Agreed, this would be very helpful.  I know the hockeyapp plugin for bitrise allows mapping files to be uploaded.

**Comment by viktorbenei** [comment]
AFAIK this was already implemented here, not sure why it was removed.. Will discuss it with the team and we'll get back ASAP! :)

**Comment by cookseym** [comment]
@godrei @viktorbenei  Thanks!  Working as desired now...no more do we have to remember to come back after CI runs to upload mapping file.

**Comment by viktorbenei** [comment]
Indeed - not sure why this was removed.. Most likely was just a mistake 🤔
