### ISSUE TITLE
Getting 500 API response

### ISSUE THREAD

**Issue by patgoley** [bitrise-steplib/steps-google-play-deploy#24]
Hey team,

Firstly, thanks for a great tool. I am having some trouble however and I'm not sure where the problem lies. When I try to execute this step, I get a 500 response from Google Play (see below). Now of course the 500 error is Google's fault for not giving us something more informative, but I'm wondering if the 500 is being caused by bad input to the API.

Upload apks
Failed to upload apk, error: googleapi: got HTTP response code 500 with body: {
 "error": {
  "code": 500,
  "message": null
 }
}

I know that the upload is "working" on some level, because I first hit other errors like not having the correct service account, the uploaded APK being debug and not release, but once I resolved those issues I started getting the 500. The YAML config for this step in my workflow is shown below:

- google-play-deploy@1.2.3:
        inputs:
        - service_account_json_key_path: "$BITRISE_SOURCE_DIR/my-service-account.json"
        - package_name: com.mycompany.myapp
        - track: beta

I do already have beta builds in Google Play that were uploaded manually, so it's not that it hasn't been configured. Any help is much appreciated!

**Comment by viktorbenei** [comment]
Hi @patgoley ,

That error (500) comes from the Google Play API, and the 500 error code means "internal server error". That's always fun to debug, as this means that an "undisclosed error happened on the server" (on the Google Play server).

> but I'm wondering if the 500 is being caused by bad input to the API.

That might be possible, although bad input should have a different error code + a message/description in the response. But the key word is *should*, everything's possible especially when talking about the Play API :)

If you can't figure out this issue please contact us through the onsite chat on bitrise.io or through email (https://www.bitrise.io/contact), and please include the build's bitrise.io URL. Maybe we can spot something in the full build log or in the config :)

**Comment by bwagnerr** [comment]
Just to note:
This happened to my today and the fix was to login to google play console and answer the new required question "Is your application suitable for children?". After I answered it, the build passed normally.

**Comment by viktorbenei** [comment]
Good catch @bwagnerr , thanks for sharing! :)

@patgoley can you please check this too? I'll close this issue for now, but feel free to comment if this would not solve the issue for you and we'll reopen it.

**Comment by patgoley** [comment]
Thanks @bwagnerr. Can you point me to where this question is in the Google Play console? I've looked around quite a bit but can't seem to find it. Any direction you can provide is much appreciated.

**Comment by bwagnerr** [comment]
Hey @patgoley, sorry I wasn't the one who fixed it, but I asked here and in my case it was a question "Is your application suitable for children?", on the same place that you answer if your application uses export level cryptography.

Hope it helps!
