### ISSUE TITLE
Abillity to have release message

### ISSUE THREAD

**Issue by ritave** [bitrise-steplib/steps-google-play-deploy#3]
In our repository we have a `WHATSNEW` file where we write our message that will be seen by the users when the application is published. I would like to use this step and use this file to publish my application with a changelog

**Comment by viktorbenei** [comment]
Thank you for the request, we'll try to implement this as soon as possible - or you can send us a Pull Request too, if you have the time to implement this.

**Comment by godrei** [comment]
Hi @ritave ,
the problem with adding `RecentChanges` section to the deploy: what's new can only submitted per language.

So we need to assign language to changelog in the publish request and also we need to solve to handle multiple changelogs for multiple languages.

I feel we can not solve this in a single input, working with only one language-changelog combination also does not seems to be a proper solution.

Currently what i can imagine as solution would be to provide the changelog as a json file, where you can assign your translated changelogs to the different languages, something like this:

```
{
  "en-US": "My changes in english",
  "de": "My changes in german"
}
```
and add an input to the step: `changelog_json_file_path`.

But this requires the users to keep and update this changelog.json file int repo, which is not the best solution...

@ritave what do you think?

**Comment by godrei** [comment]
Hi @ritave ,
i will close this ticket due to lack of information, but feel free to answer my previous question and i will reopen and manage to solve the issue.

**Comment by ritave** [comment]
@godrei Sorry, I didn't see your message before. I think the best idea would be to replicate how Android is doing it, because that's what developers are used to. It's very similar to your second option.

[Here's a link to Android's documentation](https://developer.android.com/training/basics/supporting-devices/languages.html)

**Comment by godrei** [comment]
@ritave 

What do you think about this:

Step would get a new input: `whatsnews_dir`. This input specifies localised whatsnew files directory. This directory should contain subfolders with each local you want to support, with a whatsnew file.

```
+ - [PATH/TO/WHATSNEWS]
    |
    + - [en-US]
    |   |
    |   + - whatsnew
    |
    + - [de-DE]
        |
        + - whatsnew
```

**Comment by ritave** [comment]
@godrei Since there won't be any additional files in each directory maybe we can shorten the hierarchy a bit?

How about this:
```
+ - [PATH/TO/WHATSNEWS]
    |
    + whatsnew-en-US
    |
    + whatsnew-de-DE
```

The endings would correspond to the same language codes as in Android.

**Comment by godrei** [comment]
@ritave even better, i will go with this version! Thanks for the info!

**Comment by godrei** [comment]
@ritave new version [1.1.0](https://github.com/bitrise-steplib/steps-google-play-deploy/releases/tag/1.1.0) will be available in the steplib in ~10mins with the new `whatsnews_dir` input.

**Comment by verygreenboi** [comment]
Something is unclear to me and I don't know if this is the right pace to ask. Where would this directory reside?

**Comment by ubuntudroid** [comment]
@verygreenboi you can define the directory in step setup:

![image](https://user-images.githubusercontent.com/519867/88383253-789e5c00-cdaa-11ea-8f97-27ce0c3dec5b.png)
