### ISSUE TITLE
Log tells mapping file was uploaded, but the file is missing in Google Play.

### ISSUE THREAD

**Issue by methodus** [bitrise-steplib/steps-google-play-deploy#32]
Hi,

I was wondering, why the mapping.txt is missing in Google Play although it should be uploaded by the deploy step:

```
+------------------------------------------------------------------------------+

| (5) google-play-deploy                                                       |
+------------------------------------------------------------------------------+
| id: google-play-deploy                                                       |
| version: 1.4.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-02-22T20:23:10Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[20:23:10] Start installing (golang) with apt-get       
INFO[20:23:10]  * [OK] Step dependency (go) installed, available. 
Configs:
- JSONKeyPath: https://con***06d
- PackageName: *****
- ApkPath: /bitrise/deploy/app-release-bitrise-signed.apk
- Track: beta
- UserFraction: 0.5
- WhatsnewsDir: 
- MappingFile: /bitrise/deploy/mapping.txt
- UntrackBlockingVersions: true
Authenticating
Authenticated client created
Create new edit
 editID: *****
List track infos
 production versionCodes: [4020]
 rollout versionCodes: [5015]
Upload apks
 uploaded apk version: 5016
 uploaded mapping file for apk version: 5016
Update track
 updated track: beta
 assigned apk versions: [5016]
Deactivating blocking apk versions
 possible tracks to update: []
No blocking apk version found
Validating edit
Edit is valid
Committing edit
Edit committed
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | google-play-deploy                                            | 25 sec   |
+---+---------------------------------------------------------------+----------+
```

When I open Android Vitals and Deobfuscation files I have to upload the file again:

![missing mapping](https://preview.ibb.co/noUnSc/screenshot.jpg)

The mapping file is created successfully and when I download from Bitrise and upload it to Play manually, it works. It would be very handy to have that done automatically.

**Comment by viktorbenei** [comment]
We'll check it ASAP, thanks for reporting @methodus !

If possible can you please copy paste the related bitrise.io build's URL? Would help a lot in debugging!

**Comment by methodus** [comment]
https://www.bitrise.io/build/093b49e16dc07103

**Comment by uddyami** [comment]
this is happening for me too

**Comment by trapacska** [comment]
Thank you for the reports! It was very helpful. Seems like since couple of weeks Google has issue with this endpoint.

As the investigation pointed out, the mapping file is:
- generated
- found by the step
- uploaded

However Google's Developer API doesn't handle this. Already contacted them and they said they are working on already.

Waiting for the response from their side, hope it will be sorted soon.

**Comment by uddyami** [comment]
it works now !! thanks for fixing it :)

**Comment by viktorbenei** [comment]
Glad to hear @uddyami ! :)

@methodus can you please confirm that it works for you too?

**Comment by trapacska** [comment]
Yep, Google just confirmed that they have the issue fixed.
Thank again for reporting! 🚀
