### ISSUE TITLE
Should we be concerned about the security of the JSON file?

### ISSUE THREAD

**Issue by sklink** [bitrise-steplib/steps-google-play-deploy#33]
It's a fairly permissive key file with access to manage the store listing and production APK--unless I'm using the wrong file?

I'd prefer not to commit to the repo because that leaves it on all of our developers' computers. 
Public URL means anyone could happen upon it.

Suggestions?

**Comment by viktorbenei** [comment]
Hi @sklink ,

Indeed you **should not commit** that (or any private file) into your repo.

The preferred solution is to upload the file to bitrise.io, in the workflow editor -> code signing tab, as a file. That will store it encrypted, and the build will get a time limited, expiring download URL to get that file. You can find more info at: http://devcenter.bitrise.io/tutorials/how-to-use-the-generic-file-storage/

When you upload the file you'll see what env var will include the download URL during the build - you can use that env var with the related steps. 

As noted in the step's related input (**Service Account JSON key file path**) you can specify the download url env var there as the value directly, and the step will download it to a temporary location and use it from there during the build (then the file will be discarded along with the whole VM when the build finishes).

If you'd have any questions just let us know! :)

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
