### ISSUE TITLE
Support new internal track

### ISSUE THREAD

**Issue by hanspeide** [bitrise-steplib/steps-google-play-deploy#35]
Google Play Dev Console has a new internal test track, that should be used "[..] if you want to quickly distribute your app for internal testing and quality assurance checks.". 

It would be nice to see this supported in this lib.

Details:
https://support.google.com/googleplay/android-developer/answer/3131213

**Comment by viktorbenei** [comment]
Supported in v1.4.2 ;) https://github.com/bitrise-steplib/steps-google-play-deploy/releases/tag/1.4.2

If you'd have any questions or issues just let us know!
Happy Building! :)
