### ISSUE TITLE
How to Upload Expansion Files?

### ISSUE THREAD

**Issue by randalvance** [bitrise-steplib/steps-google-play-deploy#37]
We have an apk that exceeds 100mb and have added some of the assets to an OBB file. Is there a way to upload it together with the APK?

**Comment by godrei** [comment]
Hi, sorry for my late response.
We scheduled to look at this, sorry for the inconveniences.

**Comment by trapacska** [comment]
Hey!

This issue is solved in the next release: https://github.com/bitrise-steplib/steps-google-play-deploy/releases/tag/1.5.0

Closing this ticket now but feel free to let us know if you encounter any issue with it.

🚀
