### ISSUE TITLE
Support for other closed test tracks than alpha

### ISSUE THREAD

**Issue by ricklancee** [bitrise-steplib/steps-google-play-deploy#38]
Google play provides the option to create multiple named closed test tracks. For instance we have an closed "pre-release" track and the normal Alpha track.

Are there any plans to support deploying to these other tracks?

**Comment by trapacska** [comment]
Hey @ricklancee !

I've added this to our internal tracker, we will notify you as soon as the task is evaluated and scheduled. Thank you!

**Comment by trapacska** [comment]
Hey!

This issue is solved in the next release: https://github.com/bitrise-steplib/steps-google-play-deploy/releases/tag/1.5.0

Closing this ticket now but feel free to let us know if you encounter any issue with it.

🚀
