### ISSUE TITLE
key_file_path not found

### ISSUE THREAD

**Issue by kinosang** [bitrise-steplib/steps-google-play-deploy#4]
I've already upload p12 file onto `workflow/Generic File Storage` and type the Environment Variable into the workflow. But it still show the error.

**Comment by godrei** [comment]
Hi @kinosang 
this step's `key_file_path ` should be a file path. If you upload your p12 file into `Generic File Storage`, bitrise will upload it, and provide an environment to the file's remote `URL`. 
So you should download the file, before use as `key_file_path `.
This articel on [bitrise devcenter](http://devcenter.bitrise.io/docs/how-to-use-the-generic-file-storage-with-any-step) explains how you can use `Generic File Storage` and also includes an example, how you can download the stored file.

**Comment by kinosang** [comment]
Got it.
