### ISSUE TITLE
googleapi: got HTTP response code 500

### ISSUE THREAD

**Issue by ilonashub** [bitrise-steplib/steps-google-play-deploy#40]
Hey,

We've started to have a failed step today, with the text: 
```
Validating edit
Failed to validate edit, error: googleapi: got HTTP response code 500 with body: {
 "error": {
  "code": 500,
  "message": null
 }
}
```

We are in the latest version (1.4.3), and we've never had such an issue before. Reading past issues regarding this didn't help me in figuring this out. Is there any ongoing issue now?

**Comment by ilonashub** [comment]
In case it might help someone else - our issue was that we had another active beta version in google play, and the new version tried to override it without success. We had to dismiss the current beta version for the build to pass.

**Comment by viktorbenei** [comment]
Thanks for reporting @ilonashub ! I'm sure it'll help others in the future! ;)

We're also checking if we could print more information about these issues. The main problem is that a `500` error means "Internal Server Error" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) which of course comes from the Google Play API in this case, and internal server errors are the unexpected errors, and so the server usually don't provide more information / additional details..

Anyway we're checking if we could somehow get more details and present it, but can't promise anything as it might be out of our control.

Happy Building! :)
