### ISSUE TITLE
Failed to upload mapping file, error: googleapi: Error 403: Symbol file invalid., invalidSymbolFile

### ISSUE THREAD

**Issue by mobee-bill** [bitrise-steplib/steps-google-play-deploy#44]
I am trying to deploy a new production version of my application and have been receiving the error posted when trying to deploy to google playstore.  I found that my previous version of the app still uploads successfully however my new version fails.  The only major change I have made is removing Mixpanel.  The only references I can find to this error point to proguard, but I do not have any mixpanel relevant lines in there.  Is there something I could be missing? I have attached my logs.
Thanks
[ebcc79004403ef7e.log](https://github.com/bitrise-steplib/steps-google-play-deploy/files/2515635/ebcc79004403ef7e.log)

**Comment by mobee-bill** [comment]
I resolved my issue by leaving the mapping file location blank. (was defaulted as $BITRISE_MAPPING_PATH).  I am not sure why this issue has only appeared to me now.

**Comment by tir38** [comment]
FWIW it was probably related to https://issuetracker.google.com/issues/74257813
