### ISSUE TITLE
Failed to upload apk, error: googleapi: Error 410: This Edit has been deleted., editDeleted

### ISSUE THREAD

**Issue by umarhussain15** [bitrise-steplib/steps-google-play-deploy#45]
I get this error while publishing the apk on alpha channel. The apk is successfully uploaded to play store and released to the channel but in bitrise this step fails. This causes my build to fail as the google-play-deploy step fails. 
What can be the issue ?

**Comment by bitce** [comment]
Hi @umarhussain15  can you please include a build URL we could look into?

**Comment by umarhussain15** [comment]
@bitce I just double checked and there were actually two builds triggered in parallel at the same time one was successful and the other fail. I think the reason was that as playstore has already a new apk from build 1 so when build 2 tried to upload the apk it failed.
Don't know why bitrise started two builds.

**Comment by bitce** [comment]
Oh I see. You can check the build parameters on the UI to see the start reason in case it was made by a trigger or something like that. It's also good practice to keep an eye on the activity page: https://app.bitrise.io/activity

**Comment by umarhussain15** [comment]
My rep had two webhooks added for bitrise, so I think this was causing two builds triggered. I will update here after verifying if this was the actual cause.

**Comment by matteinn** [comment]
Started seeing this with the step 2.0.1, rolled back to 1.x
