### ISSUE TITLE
How to supply multiple package names

### ISSUE THREAD

**Issue by icedice** [bitrise-steplib/steps-google-play-deploy#46]
I'm trying to use this step to upload a bunch of APK's to google play by supplying it the $BITRISE_APK_PATH_LIST from a gradle task step which calls AssembleRelease. But I'm confused what to put in "package name" i tied my actual package name (from manifest) but receives an error about wrong package name, I guess what i need to supply is the applicationID not the package name. But the different flavours created by AssembleRelease has different applicationId's ie. dk.toke.free and dk.toke.paid so how would i give this info to this step? Why is it necessary to provide this information in the first place?

**Comment by lszucs** [comment]
Hi @icedice,

We discussed on Intercom, but as a future reference, I'll write a short summary here.

You are right, you have to provide the applicationID. The step does not support uploading APKs at the moment.

We will migrate all our open GitHub issues to Discourse in the future and will convert this issue to a feature request when we get there, however, it will get to the backlog faster if you open a feature request at https://discuss.bitrise.io/c/feature-request.
