### ISSUE TITLE
googleapi: Error 403: APK specifies a version code that has already been used

### ISSUE THREAD

**Issue by rpekarek** [bitrise-steplib/steps-google-play-deploy#47]
We are experiencing this issue, even though it was previously closed. We've updated the version name as well as the version code from 169 to 170, 171, and finally 172, each time the production version codes number increases to our current version number under "List track infos". How is this possible? Shouldn't this represent the current version on Google Play? 

    List track infos
     production versionCodes: [172]
    Upload apks or app bundle
    Failed to upload apk, error: googleapi: Error 403: APK specifies a version code that has already been 
    used., apkUpgradeVersionConflict

    | x | google-play-deploy@1.5.1 (exit code: 1)

We also had a couple builds marked as success but did not appear to actually be updated on google play after all. Failing build: https://app.bitrise.io/build/6f360f699c846056 Succeeding build: https://app.bitrise.io/build/dc3185417a87dd72 (Separate white labels, same versions)

Note that we have previously used bitrise to successfully deploy our multiple white labels to the play store many times. Manual uploads are not a sustainable option due to the quantity of builds we are creating. 

_Originally posted by @rpekarek in https://github.com/bitrise-steplib/steps-google-play-deploy/issues/31#issuecomment-459099022_

**Comment by fehersanyi-bitrise** [comment]
Hello @rpekarek Could you try using the `Change Android versionCode and versionName` step to increment the version code with each build so this error will not come up? well at least I hope.

**Comment by rpekarek** [comment]
We have been updating both versionCode and versionName

**Comment by AlphaJuliettOmega** [comment]
The api should respond with the offending Build number, for sanity purposes.
