### ISSUE TITLE
OAuth Authorization failed: invalid_client 

### ISSUE THREAD

**Issue by kinosang** [bitrise-steplib/steps-google-play-deploy#5]
I've tried to use API Key and Service Account Key, both give me the sam error.

```
/usr/local/lib/ruby/gems/2.2.0/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:966:in `fetch_access_token': Authorization failed.  Server message: (Signet::AuthorizationError)
{
  "error" : "invalid_client",
  "error_description" : "The OAuth client was invalid."
}
	from /usr/local/lib/ruby/gems/2.2.0/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:983:in `fetch_access_token!'
	from /tmp/bitrise548982899/step_src/step.rb:113:in `<main>'
```

**Comment by viktorbenei** [comment]
Did you follow the guide in the Step's description? ( https://github.com/bitrise-steplib/steps-google-play-deploy/blob/master/step.yml#L3 )

**Comment by kinosang** [comment]
@viktorbenei yep.

**Comment by kinosang** [comment]
It's `service account` not `OAuth clients`, isn't it?

**Comment by viktorbenei** [comment]
Correct, you have to use `service account`.

**Comment by viktorbenei** [comment]
Did you use the **Service account** email?

**Comment by kinosang** [comment]
What's the Service account email? I didn't find any email address on Google APIs Console.

**Comment by kinosang** [comment]
Oh, got it. It's list on Play Store Developer Console.

**Comment by kinosang** [comment]
It works well now. Thank you.

**Comment by viktorbenei** [comment]
😊
