### ISSUE TITLE
Listing language en-GB not supported

### ISSUE THREAD

**Issue by mwttayler** [bitrise-steplib/steps-google-play-deploy#51]
I have a whatsnew file named whatsnew-en-GB.txt but when trying to deploy I'm getting the following error:

Failed to update listing, error: googleapi: Error 400: Listing language en-GB.txt is not supported., unsupportedListingLanguage

**Comment by bitce** [comment]
Hi @mwttayler! Seems like a response from Google, can you send us the related build URL? Or did you already find the solution?
