### ISSUE TITLE
googleapi: Error 403: Forbidden, forbidden

### ISSUE THREAD

**Issue by alexshikov** [bitrise-steplib/steps-google-play-deploy#53]
When I'm trying to upload a new alpha build, I get an exception that I can't actually understand:

```
Authenticating
Authenticated client created

Create new edit
Failed to perform edit insert call, error: googleapi: Error 403: Forbidden, forbidden
```

- the API-JSON seems correct as we've successfully authenticated (though it's brand new, previous builds have been uploaded manually).  
- the app with the provided package name does exist.  
- the version and the code of the uploaded APK are higher than the last uploaded one.  
- the API-JSON has never been used before, previous builds have been uploaded manually.

The only concern I have, there is no production/beta builds in the Dev Console, can this be the case?

What would you recommend to try/check?

**Comment by fehersanyi-bitrise** [comment]
Hello @alexshikov 

Are you sure that you defined every permission in the JSON file?

```
4. Grant the necessary rights to the service account:
  
    Visit the [Google Play Console](https://play.google.com/apps/publish) -> Settings -> Users & permissions -> Invite new user.
    Due to the way the Google Play Publisher API works, you have to grant at least the following permissions to that service account:
      - ACCESS LEVEL: View app information
      - RELEASE MANAGEMENT: Manage production releases, Manage testing track releases
      - STORE PRESENCE: Edit store listing, pricing & distribution
```
from: https://github.com/bitrise-steplib/steps-google-play-deploy/blob/master/step.yml#L24

**Comment by alexshikov** [comment]
Thank you @fehersanyi-bitrise ! We've missed it indeed. Adding permission helped.

**Comment by mobile-dualbootpartners** [comment]
You can also create a service account to access the API from a build server without providing your personal user credentials:

1. Go to the API Access page on the Google Play Console.
2. Under Service Accounts, click Create Service Account.
3. Follow the instructions on the page to create your service account.
4. Once you've created the service account on the Google Developers Console, click Done. The API Access page automatically refreshes, and your service account will be listed.
5. Click Grant Access to provide the service account the necessary rights to perform actions.
