### ISSUE TITLE
Error 400: Listing language pt-BR.txt is not supported., unsupportedListingLanguage

### ISSUE THREAD

**Issue by duanniston** [bitrise-steplib/steps-google-play-deploy#54]
`Update track
 updated track: rollout
 assigned apk versions: [40101]
Deactivating blocking apk versions
 possible tracks to update: [beta alpha]
 checking apk versions on track: beta
 versionCodes: []
Mismatching apk count, removing ([]) versions from track: beta
 checking apk versions on track: alpha
 versionCodes: []
Mismatching apk count, removing ([]) versions from track: alpha
Desired versions deactivated
Update listing
 updating recent changes for version: 40101
Failed to update listing, error: googleapi: Error 400: Listing language pt-BR.txt is not supported., unsupportedListingLanguage`

**Comment by bitce** [comment]
Hi @duanniston!

Sorry to hear about the issue, could you send us the related build URL?

**Comment by pamartineza** [comment]
@duanniston remove the ".txt" from your file name
