### ISSUE TITLE
Deploy to multiple flavors to different apps on Play Store

### ISSUE THREAD

**Issue by richardansell** [bitrise-steplib/steps-google-play-deploy#56]
How would it be possible to use $BITRISE_APK_PATH_LIST envvar to deploy each APK flavor to different apps on the Play Store rather than a single app?

**Comment by bitce** [comment]
Hi @richardansell, can you please send us a build URL where this is happening to you? The path list should contain all APKs.

**Comment by richardansell** [comment]
> Hi @richardansell, can you please send us a build URL where this is happening to you? The path list should contain all APKs.

Hi @bitce, the problem is actually to do with the deployment of each APK flavor to different apps on the Play Store as I understand the path list contains all of the apps/flavors. It seems the Google Play Store Deploy step only allows the deployment of a single app to the store, rather than cycle through each flavor and deploy to different apps

**Comment by bitce** [comment]
@richardansell I understand, can you please still include a logfile or an URL we could check out about this?
