### ISSUE TITLE
Upload to PlayStore fails with 403, replacingBundleWithApk

### ISSUE THREAD

**Issue by OleMussmann** [bitrise-steplib/steps-google-play-deploy#57]
Version `google-play-deploy@1.6.1`. Upload to the PlayStore fails with:

```
Upload apks or app bundle
Failed to upload apk, error: googleapi: Error 403: You cannot insert a bundle with the same version code as an APK in the edit., replacingBundleWithApk
```

What is 'the edit' mentioned in the error message? Also - as far as I know - we don't build any app bundles.

**Comment by bitce** [comment]
Hi @OleMussmann!

The error message printed out is the exact response from Google's API after your submission. Can you send us the related build URL?

**Comment by OleMussmann** [comment]
Hi @bitce!

Thanks for investigating with me. This is the URL: https://app.bitrise.io/build/4dca624c1f044989

**Comment by bitce** [comment]
Of course! Do you certainly not have a _bundle_ uploaded with the same version code as this APK? I think that's what the error means to say

**Comment by OleMussmann** [comment]
I do have a bundle uploaded, with version code `1`. However, the APK version number is bumped every run with the `Set Android Manifest Version Code and Name` step.

**Comment by bitce** [comment]
I see that step being in place, but is your Flutter app certainly using that for these details? For every one of your builds our Deploy to Bitrise step prints out the same data about the app (`version_code:1 version_name:1.0.0`)

**Comment by OleMussmann** [comment]
Yes, that was the missing piece! For flutter tweaking the `AndroidManifest.xml` is not sufficient (or even necessary?). If anybody else stumbles upon this, change the version-numbers and -codes in the following files will do the trick:

```
android/app/src/main/AndroidManifest.xml
pubspec.yaml
android/app/build.gradle
```

Thanks a lot @bitce for your detective work!

**Comment by bitce** [comment]
Awesome news! Of course, happy to have helped :) I'd assume it isn't necessary, but this wasn't clear to me either, just noticed the lack of change. 

Happy building! 🎉

**Comment by alexander-potemkin** [comment]
Indeed - it is a different build.graddle in different cases (was android/app/build.gradle in mine)
