### ISSUE TITLE
Failed to validate edit, error: googleapi: Error 403: releaseValidationErrorKeyApkNoUpgradePaths

### ISSUE THREAD

**Issue by rajiac2607** [bitrise-steplib/steps-google-play-deploy#60]
'Deploy to Goolge play' step in the workflow throws the below error

 Failed to validate edit, error: googleapi: Error 403: You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs., releaseValidationErrorKeyApkNoUpgradePaths

version code seems to be incremented in the 'Change versioncode and version name' step,I have mentioned version code only in build.gradle
APK signing is working

**Comment by bitce** [comment]
HI @rajiac2607!

Can you please send us the related build's URL so we can check out the logs?

**Comment by rajiac2607** [comment]
Hi @bitce,

Thanks for the support
 https://app.bitrise.io/build/c593690d762d354a#?tab=log is the build url for the failed build

**Comment by bitce** [comment]
Sure thing @rajiac2607! 

Is it possible that you have a release with higher version code uploaded already than 27?

**Comment by rajiac2607** [comment]
that is true ,there is already a build in alpha with higher version code.
if I deactivate that build will it work ? because we cannot permanently delete a version from playstore

**Comment by rajiac2607** [comment]
Closing the ticket as the real problem is identified and possible solutions exists
Thanks @bitce

**Comment by bitce** [comment]
Awesome, glad to hear that @rajiac2607, great work!
