### ISSUE TITLE
The bundle targets unrecognized languages: fb.,

### ISSUE THREAD

**Issue by anka-213** [bitrise-steplib/steps-google-play-deploy#64]
Very similar to issue #61.

This suddenly happened to me. I tried to make a new build of the exact same version of the code and the first build uploaded successfully while the second build failed to upload with this error `Failed to upload app bundle, error: googleapi: Error 403: The bundle targets unrecognized languages: fb., apkNotificationMessageKeyBundleTargetsInvalidLanguage`. The only thing I had changed was adding a secret with an API key for the Google Places API.

**Comment by marshallcool** [comment]
@anka-213 are you .aab build ?

**Comment by RiusmaX** [comment]
Same problem here with an .aab

**Comment by bradenpowers** [comment]
I am seeing the issue as well

**Comment by ltanhswd** [comment]
same problem here, any solution?

**Comment by matt-dalton** [comment]
+1

**Comment by hery-finimize** [comment]
Someone seems to have figured it out

https://gitmemory.com/issue/facebook/facebook-android-sdk/614/547914509

**Comment by anka-213** [comment]
@marshallcool Yes. Changing back to apk fixes the issue. The confusing thing is that the .aab build worked previously with the exact same code.

**Comment by anka-213** [comment]
@hery-finimize What is gitmemory and why do you link to that instead of directly to the github issue?

**Comment by hery-finimize** [comment]
@anka-213 Not sure really, that's what Google indexed. Is there anything wrong with it?

**Comment by ltanhswd** [comment]
I found the solution, update file build.gradle (android/app)

    bundle {
        density {
            enableSplit true
        }
        abi {
            enableSplit true
        }
        language {
            enableSplit = false
        }
    }

**Comment by marshallcool** [comment]
@ltanhswd better add language restriction `resConfigs "en", "US"` in build.gradle

**Comment by bradenpowers** [comment]
> @ltanhswd better add language restriction `resConfigs "en", "US"` in build.gradle

Thanks! This worked for my issue.

**Comment by VickySalunkhe** [comment]
Inside (app level) build.gradle 
add ` resConfigs "en", "US"`

```
defaultConfig {
    resConfigs "en", "US"
}
```
It resolved my issue
Thanks to @marshallcool 

Added this comment to bring more clarity.

**Comment by sungjin0213** [comment]
This was original thread in Facebook issue: https://github.com/facebook/facebook-android-sdk/issues/614

And if you need to support more than one locale, below is the way to do it from user **iutinvg**.

> will the reConfig fix work if my app needs to support 2 locales?

Just list all necessary locales:

```
resConfigs "en", "US", "ru"
```

Here's the source: https://github.com/facebook/facebook-android-sdk/issues/614#issuecomment-549770628

**Comment by Faizi-Apps** [comment]
> @ltanhswd better add language restriction `resConfigs "en", "US"` in build.gradle

Thanks
