### ISSUE TITLE
Support Internal App Sharing?

### ISSUE THREAD

**Issue by RHMDHDYT** [bitrise-steplib/steps-google-play-deploy#65]
It would be helpful to have an Internal App Sharing track for dynamic module testing. Do you have a plan to support this? Thanks

**Comment by rodrigoarias** [comment]
I think it's already done, the internal channel.
At least I'm reading this in the 2.0.1 version:

> Can be one of the built-in tracks: internal, alpha, beta, rollout, production.

**Comment by RHMDHDYT** [comment]
hi @rodrigoarias internal on that means Internal test. It's different.

**Comment by bitce** [comment]
Hi @RHMDHDYT!

Yes, we have definite plans, the task is in progress, stay tuned!

**Comment by uddyami** [comment]
hey any update for us on this?

**Comment by nair25** [comment]
Try Flybuilds - Flybuilds is the fastest way for developers to create a team and share in-development iOS/Android App for beta testing through their personal cloud in a highly secure manner.
https://www.flybuilds.com/

**Comment by androideveloper** [comment]
Any updates here?

**Comment by vadimleonov** [comment]
@bitce any updates?

**Comment by bitce** [comment]
We will make sure to update this thread once we've made progress on the initiative!

**Comment by RHMDHDYT** [comment]
still important to me

**Comment by androideveloper** [comment]
still important here too

**Comment by Roland-Bak** [comment]
Thank you for your feedback everyone 🙂
We will keep working on this, and get back to you as soon as there is an update!

**Comment by istvankovacs-bitrise** [comment]
Hello,

It's Istvan here from the Bitrise CoreSteps Team. Thanks for reaching out helping us and the mobile community to have a better experience with Bitrise steps. 💜

We started to have a broader review of all the open issues and PRs and we are continuously prioritizing these in our sprints.

We reviewed this issue and we found it to be a valid feature request. We are collecting new feature requests on our [Discuss forum](https://discuss.bitrise.io/c/feature-request/) where you can upvote and discuss further details. As this one is on our current roadmap, I close the issue and we'll share an update once we released the new version of the step. Until then, feel free to create a feature request and share your thoughts on Discuss.

Happy building! 🚀
