### ISSUE TITLE
Getting rolloutNotPermittedOnDraftApp on draft application 

### ISSUE THREAD

**Issue by kokhong20** [bitrise-steplib/steps-google-play-deploy#68]
Hi, I have encountered an issue in google-play-deploy@3.0.0.

Background: 
I have a draft application in Google Play Console and when I try to publish to internal track. I have encountered the error as below:
```
Update track
Listing tracks
internal track:
- '1.0.0' release versionCodes: [], status: 'draft'
internal track will be updated.
Release version codes are: [2]
 updated track: internal
Track updated
Validating edit
Failed to validate edit, error: googleapi: Error 400: Only releases with status draft may be created on draft app., rolloutNotPermittedOnDraftApp
```

**Comment by cavillo** [comment]
@kokhong20 you may have to close the release draft that you have in Google Play Console. After that try submitting the .aab again.

**Comment by kokhong20** [comment]
I still faced the same issues when I trying to deploy the draft application. According to the documentation (https://developers.google.com/android-publisher/api-ref/edits/tracks), we need to supply the ReleaseStatus as well. This might cause this issue. In the code now only support completed and inProgress (https://github.com/bitrise-steplib/steps-google-play-deploy/blob/8dba7be97b04c53fb2a573f910b76436f032e550/publish.go#L17). Can we open out a new input field and let the user enter their release status?

**Comment by kokhong20** [comment]
similar issues in fastlane supply plugin https://github.com/fastlane/fastlane/issues/15693

**Comment by bitce** [comment]
Hi @kokhong20!

Can you please send us a related build URL we could investigate?

**Comment by kokhong20** [comment]
Hi @bitce,
The build's URL is a private repository (from my organisation). Hence I can't send the build URL to you.
**Steps to replicate:**
1. Create a draft application in google play console
2. Use google play deploy 3.0.1
3. Set "track" to internal
4. I got this error. 

I have changed to use fastlane supply with the following configuration and it works fine now.
```
supply ( 
    apk: "Path to APK",
    release_status: 'draft',
    track: 'internal'
)
```

The main cause I suspected is as currently google-play-deploy always defaults the `ReleaseStatus` to `completed` as seen in here https://github.com/bitrise-steplib/steps-google-play-deploy/blob/8dba7be97b04c53fb2a573f910b76436f032e550/publish.go#L210

Based on google play documentation:
```
The desired status of this release.

Acceptable values are:
"completed"
"draft"
"halted"
"inProgress"
``` 

We need to supply status draft for draft application explicitly. That is my assumption.

**Comment by Roland-Bak** [comment]
Hey there @kokhong20 , you can actually send the URL link of the Build after you enable Support Access (https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/), which enables us to take a closer look and confirm your suspicions 🙂

**Comment by darekDonkey** [comment]
Hey @Roland-Bak . We have the same issue, we are trying to publish to draft app on Play store, and we are getting:

```
Validating edit
Failed to validate edit, error: googleapi: Error 400: Only releases with status draft may be created on draft app., rolloutNotPermittedOnDraftApp
```

We have enabled support access, and the failed build URL is:
[https://app.bitrise.io/build/89e33aadbdde1da0#](https://app.bitrise.io/build/89e33aadbdde1da0#)

I think there should be an option to set "hardcoded" status to be used via UI/yaml file for each workflow/build.

**Comment by nissaFaheem** [comment]
I am trying to publish the app to internal track and am getting the following error:
Failed to upload APKs: failed to upload mapping file, error: googleapi: Error 403: Symbol file invalid., invalidSymbolFile

How do I fix it?

**Comment by bitce** [comment]
Hi @nissaFaheem,

That sounds like a separate issue. Can you please contact us directly about it or raise a separate issue thread? Thanks!

**Comment by non-binary** [comment]
This is a valid issue. I have created a ticket internally for our engineering team to investigate further. I have also created a subtask for them to follow-up here once it has been fixed.

**Comment by bandojulio** [comment]
Hi @non-binary,

any updates on this? I have the same error.

**Comment by non-binary** [comment]
No update yet.

**Comment by EduardoAlberti** [comment]
Hi @luna-kx 
any updates on this?

**Comment by cathyharmon** [comment]
Hello,

I apologize for the delay.  This issue is being investigated to determine what the best resolution is.  This is progressing but unfortunately, there are no details that can be shared concerning any final resolution.

**Comment by EtienneLeni** [comment]
Hi,
Any news here ? It seems that it is quite a blocking issue.
What would be the workaround ?

**Comment by bannzai** [comment]
I faced same issue. Is this [workaround](https://github.com/bitrise-steplib/steps-google-play-deploy/issues/68#issuecomment-566363416) likely to be effective? Could you tell me the reason why it is not fixed issues? I would like to know other traps before prepare fastfile about setting `track: draft`. Thank you.

**Comment by istvankovacs-bitrise** [comment]
The [3.3.0](https://github.com/bitrise-steplib/steps-google-play-deploy/releases/3.3.0) version of the Step has just been released which provides an input for the `Status`.
