### ISSUE TITLE
Upload multiple APKs

### ISSUE THREAD

**Issue by tamifist** [bitrise-steplib/steps-google-play-deploy#7]
I would like to upload multiple(ABI specific) APKs. Could I specify multiple files in apk_path?

**Comment by viktorbenei** [comment]
You can use more than one of this step - would that work?

**Comment by viktorbenei** [comment]
to answer your question: this step right now only accepts a single path

**Comment by tamifist** [comment]
I have manually uploaded an apk for ARM(version 131252) and another one for x86( version 196788). Versions for both apks assigned automatically based on configuration and version code from AndnroidManifest.xml(versionCode="180").
Now I am trying upload new build(versionCode="181") using this step, apk_path pointing to APK for ARM(version 131253), but getting error:

> Devices with version 196788 of this app would be downgraded to version 131253 if they met the following criteria: [(API_LEVEL in range 18-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[x86_64 (arm64-v8a)*, x86_64 (armeabi-v7a)*, x86 (armeabi-v7a)*]] AND GL_ES_VERSION in range 131072-0 AND FEATURES containing all of [android.hardware.FAKETOUCH, android.hardware.LOCATION, android.hardware.location.GPS, android.hardware.location.NETWORK, android.hardware.WIFI])].

bitrise log:
[log.txt](https://github.com/bitrise-steplib/steps-google-play-deploy/files/490167/log.txt)

I can try second step to upload apk for x86, but I am expecting the same problem...

**Comment by tamifist** [comment]
APKs should be uploaded in single edit, so I can't use more than one step

**Comment by tamifist** [comment]
Any updates?

**Comment by godrei** [comment]
Hi @tamifist , 
we scheduled the task to this sprint, so it will be done on this week.

**Comment by methodus** [comment]
I'd like to upvote this. Its a very handy feature to keep APKs with native libraries small.

**Comment by tamifist** [comment]
Yeah, we need it now to reduce apk size for our prod version. @godrei Could you please let me know when ready? Thank you!

**Comment by tamifist** [comment]
Any udpates?

**Comment by godrei** [comment]
Hi @tamifist , 
sorry for my late response, i was working on the new xamarin steps. Tomorrow i will start to work on your request.

**Comment by tamifist** [comment]
Hi @godrei, still in progress?

**Comment by godrei** [comment]
Hi @tamifist 
new version [1.0.0](https://github.com/bitrise-steplib/steps-google-play-deploy/releases/tag/1.0.0) is available in the steplib, the `apk_path` input now supports multiple APK paths separated by `|` character like: `/path/to/my/app1.apk|/path/to/my/app2.apk|/path/to/my/app3.apk`
