### ISSUE TITLE
User fraction range issue

### ISSUE THREAD

**Issue by IvanVatov** [bitrise-steplib/steps-google-play-deploy#73]
Getting configuration
Couldn't create config: failed to parse config:
- UserFraction: 1.0: value 1.000000 is out of range 0.000000-1.000000

**Comment by AndrazP** [comment]
Hi @IvanVatov,
I have the same issue. How did you fix it?

**Comment by IvanVatov** [comment]
Hi @AndrazP, read the field description carefully. If you want full rollout, leave the field blank! Stupid but fact.
