### ISSUE TITLE
Failed to perform edit insert call, error: googleapi: Error 400: Invalid JSON payload received

### ISSUE THREAD

**Issue by anatter** [bitrise-steplib/steps-google-play-deploy#74]
Hi,

I am suddenly receiving the following error when deploying to google play store:

`Failed to perform edit insert call, error: googleapi: Error 400: Invalid JSON payload received. Unknown name "": Root element must be a message., invalid`

**Comment by esthor** [comment]
I'm also having this problem

**Comment by bitce** [comment]
Hi @anatter  and @esthor! We are currently looking into this, will update you soon.

**Comment by rolandsarosy** [comment]
Just to chime in, the same is happening with our deployments. Thanks for working on the issue guys!

**Comment by rodrigoarias** [comment]
Same here!

**Comment by bitce** [comment]
Thanks for the patience guys, a new version of the step was released containing the fix: https://github.com/bitrise-steplib/steps-google-play-deploy/releases/tag/3.0.2

**Comment by rolandsarosy** [comment]
Do you have an ETA on when it is going to be available in the workflow editor? The latest I'm seeing currently is 3.0.1
![Screenshot 2020-03-05 at 17 09 00](https://user-images.githubusercontent.com/36110029/76000456-049b0e80-5f04-11ea-942a-5f6560279acf.png)

**Comment by bitce** [comment]
You might have to force a cache update for it to appear right away, but if you select the always latest version, that should apply to the new fixed release.

**Comment by rolandsarosy** [comment]
Very true indeed, our build succeeded. Thank you for the quick fix!

**Comment by anatter** [comment]
Thank you for the fix!
