### ISSUE TITLE
Failed to perform edit insert call, error: googleapi: Error 400: Invalid JSON payload received.

### ISSUE THREAD

**Issue by SSinfo302** [bitrise-steplib/steps-google-play-deploy#76]
Authenticating
Authenticated client created
Create new edit
Failed to perform edit insert call, error: googleapi: Error 400: Invalid JSON payload received. Unknown name "": Root element must be a message., invalid
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | google-play-deploy@3.0.1 (exit code: 1)

**Comment by HanliTheron** [comment]
I suddenly have exactly the same issue

**Comment by StepanBeznosovEvrythng** [comment]
Looks like this is a global issue, but a question is how to resolve this.

**Comment by SSinfo302** [comment]
@HanliTheron 
> I suddenly have exactly the same issue

when did you get this issue?

**Comment by SSinfo302** [comment]
@StepanBeznosovEvrythng 
> Looks like this is a global issue, but a question is how to resolve this.

when did you get this issue?

**Comment by TMC-LLB** [comment]
This issue first occurred for me yesterday 2020.03.05 @ 14:50 UTC.

Earlier build at 09:23 UTC deployed with no problems

**Comment by HanliTheron** [comment]
> @HanliTheron
> 
> > I suddenly have exactly the same issue
> 
> when did you get this issue?

I got it today at 11:57, 13:01 and 13:50. Rebuilding now with google-play-deploy@3.0.2 to see if it solves the issue.

**Comment by StepanBeznosovEvrythng** [comment]
My last successful build was at 4th March, today I have issues for last hour.
Build IDs: 44f27b0f368907f1, c019f5aa9c88eda5

**Comment by HanliTheron** [comment]
Rebuilding with google-play-deploy@3.0.2 worked, don't know if it was just a coincidence, but worth trying.

**Comment by TMC-LLB** [comment]
> Rebuilding with google-play-deploy@3.0.2 worked, don't know if it was just a coincidence, but worth trying.

Worked for me as well.

**Comment by SSinfo302** [comment]
> > Rebuilding with google-play-deploy@3.0.2 worked, don't know if it was just a coincidence, but worth trying.
> 
> Worked for me as well.

let me try

**Comment by SSinfo302** [comment]
> > > Rebuilding with google-play-deploy@3.0.2 worked, don't know if it was just a coincidence, but worth trying.
> > 
> > 
> > Worked for me as well.
> 
> let me try

not working

**Comment by StepanBeznosovEvrythng** [comment]
> Rebuilding with google-play-deploy@3.0.2 worked, don't know if it was just a coincidence, but worth trying.

Thank you, it helped!

**Comment by pregno** [comment]
`3.0.2` worked for me as well

**Comment by bitce** [comment]
Hi everyone! Apologies, we missed this thread somehow, we attended #74. Please make sure to use the latest (3.0.2) version of the step and you won't experience this issue.

**Comment by SSinfo302** [comment]
resolved
