### ISSUE TITLE
service_account_json_key_path should not be a secret

### ISSUE THREAD

**Issue by alexander-potemkin** [bitrise-steplib/steps-google-play-deploy#78]
That is misleading - service_account_json_key_path field is marked as private, despite it's just a path to the file, that is managed by BitRise (as per https://medium.com/@bitrise/how-to-deploy-your-android-app-to-google-play-store-441bc8a5bb61).

Guess, that needs to be fixed (I went directly to YAML for that purpose).

**Comment by bitce** [comment]
Hi @alexander-potemkin!

The Service Account JSON key path is more accurately a URL leading to a file you've uploaded, this is not a file managed by Bitrise. It was intentionally made a secret, so anyone leading to logs do not have access to download this file.

**Comment by alexander-potemkin** [comment]
Hi @bitce , can't agree. I can just protect the file with bitrise's protection feature, can't I?
If I want it to be a secret.

My impression also was, that it also became available during the build?

**Comment by bitce** [comment]
This is a sort of code signing identity you have to pre-upload, maybe you're thinking of the Google Services info.plist file?

I'm not 100% sure what you mean by protection feature, other than Secrets, feel free to elaborate!

**Comment by alexander-potemkin** [comment]
![Screenshot 2020-06-04 at 14 06 25](https://user-images.githubusercontent.com/2323840/83749682-bc0f0080-a66c-11ea-9d7d-3a551eda1dd6.png)

I was thinking about that

**Comment by bitce** [comment]
Oh I see! Well, there is a conflict here since you can only make secrets protected, and even if you do that means these are hidden on the website, and it does not affect builds directly. Anyhow, I'll make sure to forward your feature request about this!

**Comment by alexander-potemkin** [comment]
Thanks!
