### ISSUE TITLE
Failed to update track, reason: could not find track with name

### ISSUE THREAD

**Issue by jamesblack007** [bitrise-steplib/steps-google-play-deploy#79]
When using google-play-deploy step, I receive the following error. Specific error is : "Failed to validate edit, error: googleapi: Error 400: Track not found: **** ****" even though a track with that name exists ( see account )

Here are the relevant logs, specifically the last line which says "Failed to update track, reason: could not find track with name **** ***" even though while listing the tracks, it's clearly there. 

Getting configuration
Configs:
- JSONKeyPath: *****
- PackageName: com.valr.app
- AppPath: /Users/vagrant/deploy/app-release-bitrise-signed.apk\n
- ExpansionfilePath: 
- Track: com.valr.app dev
- UserFraction: 0
- WhatsnewsDir: 
- MappingFile: /Users/vagrant/deploy/mapping.txt
Found .apk file: /Users/vagrant/deploy/app-release-bitrise-signed.apk
Configuration read successfully
Authenticating
Authenticated client created
Create new edit
 editID: 08427639474888460051
Edit insert created
Upload apks or app bundles
Found .apk file: /Users/vagrant/deploy/app-release-bitrise-signed.apk
Uploading /Users/vagrant/deploy/app-release-bitrise-signed.apk 1/1
Uploaded apk version: 634
 uploaded mapping file for apk version: 634
Done uploading of 1 apps
New version codes to upload: [634]
Applications uploaded
Update track
Listing tracks
production track:
- '1.0.17' release versionCodes: [468 610], status: 'completed'
internal track:
- '1.0.0' release versionCodes: [354], status: 'draft'
com.valr.app dev track:
- '1.0.18' release versionCodes: [617], status: 'draft'
- '1.0.18' release versionCodes: [614], status: 'completed'
com.valr.app prod track:
- '1.0.18' release versionCodes: [468 610 633], status: 'completed'
dev track:
- '1.0.0' release versionCodes: [374], status: 'completed'
prod track:
- '1.0.0' release versionCodes: [396], status: 'completed'
Failed to update track, reason: could not find track with name com.valr.app dev

Why?

**Comment by jamesblack007** [comment]
Hello?

**Comment by jamesblack007** [comment]
Yes, I'm uploading to the right track. The logs on Bitrise shows that clearly that track exists:


Update track
Listing tracks
production track:
- '1.0.17' release versionCodes: [468 610], status: 'completed'
internal track:
- '1.0.0' release versionCodes: [354], status: 'draft'
**com.valr.app dev** track:
- '1.0.18' release versionCodes: [643], status: 'completed'
com.valr.app prod track:
- '1.0.18' release versionCodes: [648], status: 'completed'
com.valr.app staging track:
- '1.0.18' release versionCodes: [644], status: 'completed'
dev track:
- '1.0.0' release versionCodes: [374], status: 'completed'
prod track:
- '1.0.0' release versionCodes: [396], status: 'completed'
Failed to update track, reason: could not find track with name **com.valr.app dev**

**Comment by jamesblack007** [comment]
Hello?

**Comment by jamesblack007** [comment]
Anyone there?

**Comment by Roland-Bak** [comment]
Hi there @jamesblack007 👋

This issue seems like a build related problem, and not with the step itself, could you please send us a Ticket on our site, where you include the build URL and enable Support Access as well? 🙂
The experts would be happy to take a look an investigate in detail, and submitting a ticket would be the best channel to get your issue fixed! 🙂

**Comment by jamesblack007** [comment]
There is certainly something amiss. I looked through the step code that uses Android Publisher edit service.

The following log messages appear:
  
  Authenticated client created
  Edit insert created
  Applications uploaded
  Track updated
  -> Failed to validate edit, error: googleapi: Error 400: Track not found: com.valr.app prod

So, the last step above fails. Why? If the track wasn't found then the "Update track" step should have failed.

I've created a Support ticket too: **[Bitrise Case Created] - 7171**

This problem has been going on for too long without any resolution which defeats the purpose of using Bitrise since we need to manually download the AAB files and upload to Play Console ourselves.

Please investigate.

**Comment by chaitanyatanna-bitrise** [comment]
Hi @jamesblack007 
I am going to create a for the engineering team to look into this issue further.

Thanks
Chaitanya

**Comment by chaitanyatanna-bitrise** [comment]
Hi @jamesblack007 
We have checked the corresponding bitrise.yml in OP and it seems that the user is misconfiguring the track input of the step.
Actual input: com.valr.app $ENV
which is resolved to: com.valr.app prod
Expected input: $ENV
which should be resolved to: prod

Let me know if you have questions.

Thanks
Chaitanya
