### ISSUE TITLE
Can't Upload APK because 403 but Edit insert is created

### ISSUE THREAD

**Issue by pedromalta** [bitrise-steplib/steps-google-play-deploy#82]
That's the log I'm getting trying to use the step on bitrise:
What I find weird is that the Edit is being created, but the upload is failing.

``+------------------------------------------------------------------------------+

| (8) google-play-deploy@3                                                     |
+------------------------------------------------------------------------------+
| id: google-play-deploy                                                       |
| version: 3.0.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-06-10T13:56:41Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Getting configuration
Configs:
- JSONKeyPath: *****
- PackageName: fm.[REDACTED].music.alpha
- AppPath: /bitrise/deploy/app-alpha.apk
- ExpansionfilePath: 
- Track: internaltest
- UserFraction: 0
- WhatsnewsDir: 
- MappingFile: 
Found .apk file: /bitrise/deploy/app-alpha.apk
Configuration read successfully
Authenticating
Authenticated client created
Create new edit
 editID: 00542497222085258217
Edit insert created
Upload apks or app bundles
Found .apk file: /bitrise/deploy/app-alpha.apk
Uploading /bitrise/deploy/app-alpha.apk 1/1
Failed to upload APKs: failed to upload apk, error: googleapi: got HTTP response code 403 with body: Access Not Configured. Google Play Developer API has not been used in project 141409347850 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/androidpublisher.googleapis.com/overview?project=141409347850 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | google-play-deploy@3 (exit code: 1)                           | 14.70 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-google-play-deploy/issues |
| Source: https://github.com/bitrise-io/steps-google-play-deploy               |
+---+---------------------------------------------------------------+----------+
        ``

**Comment by non-binary** [comment]
Hi @pedromalta,

Can you please share a build link and enable support access in your project setting?

**Comment by pedromalta** [comment]
Hi @non-binary I enabled the support access.
The build that is giving us trouble is that one

**Comment by non-binary** [comment]
Hi @pedromalta,

Please take a look at https://github.com/bitrise-steplib/steps-google-play-deploy/issues/53.

**Comment by non-binary** [comment]
Hi @pedromalta,

Please also follow the documentation on how to set up a service user: https://devcenter.bitrise.io/deploy/android-deploy/deploying-android-apps/#setting-up-your-first-project/

**Comment by garthus** [comment]
Hi @non-binary 

I am also having this issue and also seems to be widerspread if I am correct:

https://github.com/fastlane/fastlane/issues/16593

I have also gone through the above docs many times, setup and resetup and cannot get it to deploy to the play store.

One occasion it worked but not since

**Comment by nicolasjafelle** [comment]
We are also facing this issue for our builds.

**Comment by bitce** [comment]
We're seeing other reports of the problem no longer happening. Can you guys let us know if you still get this error?

**Comment by nicolasjafelle** [comment]
Still happening to me, more specifically this one:
https://github.com/bitrise-steplib/steps-google-play-deploy/issues/87
