### ISSUE TITLE
Can this be configured to work with a brand new app?

### ISSUE THREAD

**Issue by GForceWeb** [bitrise-steplib/steps-google-play-deploy#83]
When trying to run this step with a new app ID that doesn't exist in the Google Play account yet I'm presented with this error:

`Failed to perform edit insert call, error: googleapi: Error 404: Package not found: com.myapp.app., notFound`

Checking the Play Store API account details it should be possible to create a new app via the API user. Just wondering if this can be done via this step?

**Comment by lpusok** [comment]
Hello @GForceWeb,
That is not supported at the moment. You will have to create the app first on the Google Play Console.
In addition, you have to upload the first version for every track (internal, beta...) manually first to use this step; this is planned to be improved.

**Comment by GForceWeb** [comment]
Thanks for the reply. Not the answer I was hoping for but that's ok, I'll try to find another way to work around that.
