### ISSUE TITLE
Failed to perform edit insert call, error: googleapi: Error 404: Package not found: my.package.name., notFound

### ISSUE THREAD

**Issue by AlinaPohl** [bitrise-steplib/steps-google-play-deploy#84]
I'm trying to deploy an android app to the internal track. I've set up the json file for the google api, but the Step fails:

This is the log from the Step:

```
Getting configuration
Configs:
- JSONKeyPath: *****
- PackageName: my.package.name
- AppPath: /bitrise/deploy/app-name-release.aab
- ExpansionfilePath: 
- Track: internal
- UserFraction: 0
- WhatsnewsDir: 
- MappingFile: /bitrise/deploy/app-mapping-20200615130552.txt
Found .aab file: /bitrise/deploy/app-name-release.aab
Configuration read successfully
Authenticating
Authenticated client created
Create new edit
Failed to perform edit insert call, error: googleapi: Error 404: Package not found: my.package.name., notFound
```
(Note: I changed the package name for this question)
The App is already published and was also already uploaded to the internal track of the Play Console before.
Has anybody an idea, why this happens? Why there is an extra dot added after the package name?

**Comment by non-binary** [comment]
Hi @AlinaPohl,

Please also follow the documentation on how to set up a service user: https://devcenter.bitrise.io/deploy/android-deploy/deploying-android-apps/#setting-up-your-first-project/

**Comment by AlinaPohl** [comment]
> Hi @AlinaPohl,
> 
> Please also follow the documentation on how to set up a service user: https://devcenter.bitrise.io/deploy/android-deploy/deploying-android-apps/#setting-up-your-first-project/

Yes, I did this. But with the difference, that there are multiple projects linked within the json api file, because it's a whitelabel app.

**Comment by AlinaPohl** [comment]
I've found the problem. I had to specify the flavor's explicit package name, like

`my.package.name.flavor1`
