### ISSUE TITLE
APK is not a valid ZIP archive, forbidden

### ISSUE THREAD

**Issue by mskx42** [bitrise-steplib/steps-google-play-deploy#86]
Hi, thanks for reading this issue. I've got a problem with uploading signed and ready .apk file to Google Play. There is an error:

> Upload apks or app bundles
Found .apk file: /bitrise/deploy/app-prod-release-bitrise-signed.apk
Uploading /bitrise/deploy/app-prod-release-bitrise-signed.apk 1/1
Failed to upload APKs: failed to upload apk, error: googleapi: Error 403: APK is not a valid ZIP archive, forbidden

Never seen this one and can't find solution online. Hope you can help, thanks.

**Comment by bitce** [comment]
Hi @mskx42! Can you please include a build URL here that we could check out? Thanks!

**Comment by mskx42** [comment]
Hi @bitce. Thanks for the reply. Here's build URL https://app.bitrise.io/build/1fb9b9dfa5aff23e#?tab=log

**Comment by mskx42** [comment]
Hi @bitce. Did you manage to check out what is going on?

**Comment by mskx42** [comment]
Well, it seems that this issue has resolved itself (or there was some action from your side @bitce ?).
According to this [build](https://app.bitrise.io/build/dc61fc47d8c8667c#?tab=log) our .apk was delivered to Google Play successfully.

**Comment by bitce** [comment]
Hi @mskx42!

Sorry for the delay. We did not complete any action that should have solved this, I believe there was some kind of outage with the Google Play API, since we were seeing an elevated number of seemingly unrelated but similar error messages.

**Comment by mskx42** [comment]
Sure, no problem. Thanks for help!

**Comment by SaravanarajaGITHUB** [comment]
Facing the same issue 

![Capture](https://user-images.githubusercontent.com/6235704/87006112-be212d80-c1dd-11ea-9153-2424de4dfff7.PNG)

**Comment by mskx42** [comment]
Hi @bitce! Unfortunately this issue happened again :(

**Comment by megataps** [comment]
I have update the sign apk step like this:
`- sign-apk@1:
        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
        inputs:
        - use_apk_signer: 'true'
        - debuggable_permitted: 'false'`

It worked for me. Hope this help.
