### ISSUE TITLE
Target SDK version 30 requires a minimum of signature scheme v2

### ISSUE THREAD

**Issue by nicolasjafelle** [bitrise-steplib/steps-google-play-deploy#87]
Hi !! Thanks for reading this issue. Today we tried to build our apk and upload to google play as usual but the step fails with this message:

```
Failed to upload APKs: failed to upload apk, error: googleapi: Error 403: APK signature is invalid or does not exist. Error from apksigner: ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme, forbidden
```

We were building with SDK 30 for the last week or so without any problem before. Attached a screenshot of the log. Thanks in advance!

![bitrise_error](https://user-images.githubusercontent.com/526123/86547279-d7408a80-bf0e-11ea-8775-b721ebe57f9d.png)

**Comment by nicolasjafelle** [comment]
Tried going back to Android SDK 29 and everything works Ok. No other change made

**Comment by SeleznevAM** [comment]
I have had the same problem.

**Comment by koral--** [comment]
Are you sure that you are using signing V2? You can do it using apksigner.

**Comment by SeleznevAM** [comment]
> Are you sure that you are using signing V2? You can do it using apksigner.

Yes. It's work for me. Thanks
