### ISSUE TITLE
Failed to upload: Error 400: Only releases with status draft may be created on draft app., badRequest

### ISSUE THREAD

**Issue by richardansell** [bitrise-steplib/steps-google-play-deploy#90]
I'm getting the following error message when trying to deploy my Android app to an alpha track I've create:

`Failed to validate edit, error: googleapi: Error 400: Only releases with status draft may be created on draft app., badRequest`

I've already followed the instructions closely and have also uploaded my first app as stated.

**Comment by non-binary** [comment]
Hi @richardansell,

Can you please share a link to a build and enable support access in project settings?

**Comment by richardansell** [comment]
Hi Luna,

This is the [link](https://app.bitrise.io/build/5e8e458d970f2785#?tab=log) to the last build. I've also enabled support access.

Thanks in advance for your help!

**Comment by non-binary** [comment]
Hi @richardansell,

Please read https://stackoverflow.com/a/59568679.

**Comment by richardansell** [comment]
Hi @non-binary ,

I've managed to get it to run successfully now after filling out all the required information and then publishing the rollout to the alpha internal test track. It seems you must do all of this and publish it to the track in order to get it to work, although the documentation doesn't say you need to specifically do this.
