### ISSUE TITLE
Google Play Auth Failed

### ISSUE THREAD

**Issue by kvanry** [bitrise-steplib/steps-google-play-deploy#92]
Failed to create HTTP client: failed to create auth config from json key file [REDACTED], error: %!s(<nil>)
https://app.bitrise.io/build/c6b9a6b52299dd99#?tab=log

After trying a plethora of things, I'm still getting this. Went and looked and made sure that the file is getting created in the right location.

**Comment by non-binary** [comment]
Hi @kvanry,

Please enable support access in your project's settings so I can open your build log.

**Comment by kvanry** [comment]
@non-binary That is now enabled
