### ISSUE TITLE
Support multiple mapping files when doing a multiple apk/aab release.

### ISSUE THREAD

**Issue by Stuart-campbell** [bitrise-steplib/steps-google-play-deploy#95]
As far as I can tell the plugin supports muti-apk upload (which is great) but doesn't seem to support uploading the different mappings to go with them.

**Comment by bitce** [comment]
Thanks for the feature request @Stuart-campbell!

**Comment by androideveloper** [comment]
Any updates on this? We recently found that this is the reason why we see obfuscated crashes on Google Play. Bitrise picks only one of the generated mapping files.

**Comment by Roland-Bak** [comment]
Hello @androideveloper 👋

No update yet, but as soon as we have something, we'll let you know! 🙂

**Comment by koral--** [comment]
It seems that this issue should not be closed automatically.

**Comment by ofalvai** [comment]
Hello everyone, we have released support for multiple mapping files in [version 3.6.0](https://github.com/bitrise-steplib/steps-google-play-deploy/releases/tag/3.6.0). Thank you for your patience!
