### ISSUE TITLE
Failed to validate edit, error: googleapi: Error 403: You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs., forbidden

### ISSUE THREAD

**Issue by KurasovAnton** [bitrise-steplib/steps-google-play-deploy#98]
Hi! I start getting this issue when trying to deploy APK to the google store using google-play-deploy step.  I could deploy this build manually to the store.
The google-play-deploy step works correctly a month ago.
Does anyone have the same issue?

Thank you in advance.

**Comment by bitce** [comment]
Hi Kurasov!

Sounds like this might be an issue with the versionCode and/or versionName's value being less than the already deployed versions. Have you checked if that could be the case?

**Comment by KurasovAnton** [comment]
@bitce , thank you for such fast response.
Yes, I've double-checked the build number and app version and it was greater than that one that was on google play console.
Google console latest versions:
App v2.5.0
build#4000102
Build that failed to deploy versions:
App v2.6.0
build#4000110

Also, I've downloaded the APK from the bitrise and I could deploy it manually to store.
